export enum FeedItemType {
    MY_ACTION = 'MY_ACTION',
    TEAM_ACTION = 'TEAM_ACTION',
    PLATFORM_EVENT = 'PLATFORM_EVENT',
    ASSIGNED_TASK = 'ASSIGNED_TASK',
    FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
}
