export enum AlertMetric {
  FAILED_TRANSACTION_RATE = 'FAILED_TRANSACTION_RATE',
  SETTLEMENT_FAILURE_RATE = 'SETTLEMENT_FAILURE_RATE',
  WEBHOOK_FAILURE_RATE = 'WEBHOOK_FAILURE_RATE',
  BLOCKCHAIN_BLOCK_LAG = 'BLOCKCHAIN_BLOCK_LAG',
  API_ERROR_RATE = 'API_ERROR_RATE',
  PENDING_SETTLEMENT_AGE = 'PENDING_SETTLEMENT_AGE',
  PLATFORM_WALLET_BALANCE_LOW = 'PLATFORM_WALLET_BALANCE_LOW',
  MERCHANT_SIGNUP_SPIKE = 'MERCHANT_SIGNUP_SPIKE',
  TRANSACTION_VOLUME_DROP = 'TRANSACTION_VOLUME_DROP',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AlertEventStatus {
  ACTIVE = 'ACTIVE',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  AUTO_RESOLVED = 'AUTO_RESOLVED',
}

export interface AlertCondition {
  operator: 'gt' | 'lt' | 'gte' | 'lte';
  threshold: number;
  windowMinutes: number;
}
