export enum IncidentSeverity {
  P1_CRITICAL = 'P1_CRITICAL',
  P2_HIGH = 'P2_HIGH',
  P3_MEDIUM = 'P3_MEDIUM',
  P4_LOW = 'P4_LOW',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  INVESTIGATING = 'INVESTIGATING',
  MITIGATED = 'MITIGATED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TimelineEntryType {
  STATUS_CHANGE = 'STATUS_CHANGE',
  NOTE = 'NOTE',
  INVESTIGATION_UPDATE = 'INVESTIGATION_UPDATE',
  ACTION_TAKEN = 'ACTION_TAKEN',
  RESOLUTION = 'RESOLUTION',
}
