export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  TRANSFER_INSUFFICIENT_BALANCE: 'TRANSFER_INSUFFICIENT_BALANCE',

  PIN_LOCKED: 'PIN_LOCKED',

  KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',

  TIER_LIMIT_EXCEEDED: 'TIER_LIMIT_EXCEEDED',
};