export enum DocumentType {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  CERTIFICATE_OF_INCORPORATION = 'CERTIFICATE_OF_INCORPORATION',
  MEMORANDUM_OF_ASSOCIATION = 'MEMORANDUM_OF_ASSOCIATION',
  DIRECTORS_ID = 'DIRECTORS_ID',
  DIRECTORS_PROOF_OF_ADDRESS = 'DIRECTORS_PROOF_OF_ADDRESS',
  UTILITY_BILL = 'UTILITY_BILL',
  BANK_STATEMENT = 'BANK_STATEMENT',
  TAX_CERTIFICATE = 'TAX_CERTIFICATE',
  PEP_DECLARATION = 'PEP_DECLARATION',
  SANCTIONS_DECLARATION = 'SANCTIONS_DECLARATION',
  BENEFICIAL_OWNER_FORM = 'BENEFICIAL_OWNER_FORM',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  SUPERSEDED = 'SUPERSEDED',
}
