export enum KycRejectionReason {
  FRAUDULENT_DOCUMENTS = 'FRAUDULENT_DOCUMENTS',
  INCOMPLETE_SUBMISSION = 'INCOMPLETE_SUBMISSION',
  PROHIBITED_BUSINESS = 'PROHIBITED_BUSINESS',
  HIGH_RISK_JURISDICTION = 'HIGH_RISK_JURISDICTION',
  OTHER = 'OTHER',
}
