export enum SecurityEventType {
  IP_NOT_IN_ALLOWLIST = 'IP_NOT_IN_ALLOWLIST',
  INVALID_API_KEY = 'INVALID_API_KEY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SUSPICIOUS_TRANSACTION = 'SUSPICIOUS_TRANSACTION',
  ADMIN_FAILED_LOGIN = 'ADMIN_FAILED_LOGIN',
  ADMIN_ACCOUNT_LOCKED = 'ADMIN_ACCOUNT_LOCKED',
  API_KEY_BRUTE_FORCE = 'API_KEY_BRUTE_FORCE',
  PAYLOAD_INJECTION_ATTEMPT = 'PAYLOAD_INJECTION_ATTEMPT',
}

export enum BlockReason {
  MANUAL = 'MANUAL',
  AUTO_BRUTE_FORCE = 'AUTO_BRUTE_FORCE',
  AUTO_RATE_LIMIT_ABUSE = 'AUTO_RATE_LIMIT_ABUSE',
  FRAUD = 'FRAUD',
}
